# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendships', models.ManyToManyField(related_name='friends', to='beltapp.User')),
            ],
        ),
    ]
