# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltapp', '0002_friendship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='friendships',
        ),
        migrations.AddField(
            model_name='user',
            name='friendships',
            field=models.ManyToManyField(related_name='_user_friendships_+', to='beltapp.User'),
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
